"""cabinets_ressources_d2a

Revision ID: 522fe4028976
Revises: b76b4e21c632
Create Date: 2026-10-02 23:47:18.492450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522fe4028976'
down_revision: Union[str, None] = 'b76b4e21c632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabinet_praticiens',
    sa.Column('cabinet_id', sa.UUID(), nullable=False),
    sa.Column('praticien_id', sa.UUID(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], name=op.f('fk_cabinet_praticiens_cabinet_id_cabinets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['praticien_id'], ['praticiens.id'], name=op.f('fk_cabinet_praticiens_praticien_id_praticiens'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cabinet_praticiens')),
    sa.UniqueConstraint('cabinet_id', 'praticien_id', name='uq_cabinet_praticien')
    )
    op.create_index(op.f('ix_cabinet_praticiens_cabinet_id'), 'cabinet_praticiens', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_cabinet_praticiens_id'), 'cabinet_praticiens', ['id'], unique=False)
    op.create_index(op.f('ix_cabinet_praticiens_praticien_id'), 'cabinet_praticiens', ['praticien_id'], unique=False)
    op.create_table('disponibilites',
    sa.Column('praticien_id', sa.UUID(), nullable=False),
    sa.Column('cabinet_id', sa.UUID(), nullable=True),
    sa.Column('jour_semaine', sa.SmallInteger(), nullable=True),
    sa.Column('date_specifique', sa.Date(), nullable=True),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], name=op.f('fk_disponibilites_cabinet_id_cabinets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['praticien_id'], ['praticiens.id'], name=op.f('fk_disponibilites_praticien_id_praticiens'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disponibilites'))
    )
    op.create_index(op.f('ix_disponibilites_cabinet_id'), 'disponibilites', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_disponibilites_date_specifique'), 'disponibilites', ['date_specifique'], unique=False)
    op.create_index(op.f('ix_disponibilites_id'), 'disponibilites', ['id'], unique=False)
    op.create_index(op.f('ix_disponibilites_jour_semaine'), 'disponibilites', ['jour_semaine'], unique=False)
    op.create_index(op.f('ix_disponibilites_praticien_id'), 'disponibilites', ['praticien_id'], unique=False)
    op.add_column('consultations', sa.Column('fauteuil_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_consultations_fauteuil_id'), 'consultations', ['fauteuil_id'], unique=False)
    op.create_foreign_key(op.f('fk_consultations_fauteuil_id_fauteuils'), 'consultations', 'fauteuils', ['fauteuil_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_consultations_fauteuil_id_fauteuils'), 'consultations', type_='foreignkey')
    op.drop_index(op.f('ix_consultations_fauteuil_id'), table_name='consultations')
    op.drop_column('consultations', 'fauteuil_id')
    op.drop_index(op.f('ix_disponibilites_praticien_id'), table_name='disponibilites')
    op.drop_index(op.f('ix_disponibilites_jour_semaine'), table_name='disponibilites')
    op.drop_index(op.f('ix_disponibilites_id'), table_name='disponibilites')
    op.drop_index(op.f('ix_disponibilites_date_specifique'), table_name='disponibilites')
    op.drop_index(op.f('ix_disponibilites_cabinet_id'), table_name='disponibilites')
    op.drop_table('disponibilites')
    op.drop_index(op.f('ix_cabinet_praticiens_praticien_id'), table_name='cabinet_praticiens')
    op.drop_index(op.f('ix_cabinet_praticiens_id'), table_name='cabinet_praticiens')
    op.drop_index(op.f('ix_cabinet_praticiens_cabinet_id'), table_name='cabinet_praticiens')
    op.drop_table('cabinet_praticiens')
    # ### end Alembic commands ###
