"""odontogramme_d1c

Revision ID: 6e33b6d348d0
Revises: 3d0a79ee3880
Create Date: 2026-10-02 14:46:04.624398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e33b6d348d0'
down_revision: Union[str, None] = '3d0a79ee3880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chartings_parodontaux',
    sa.Column('dent_id', sa.UUID(), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=True),
    sa.Column('date_examen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sondages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nac', sa.Integer(), nullable=True),
    sa.Column('recession', sa.Integer(), nullable=True),
    sa.Column('saignement_bop', sa.Boolean(), nullable=False),
    sa.Column('suppuration', sa.Boolean(), nullable=False),
    sa.Column('mobilite', sa.Integer(), nullable=True),
    sa.Column('furcation', sa.Integer(), nullable=True),
    sa.Column('plaque_ipv', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_chartings_parodontaux_consultation_id_consultations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dent_id'], ['dents.id'], name=op.f('fk_chartings_parodontaux_dent_id_dents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chartings_parodontaux'))
    )
    op.create_index(op.f('ix_chartings_parodontaux_dent_id'), 'chartings_parodontaux', ['dent_id'], unique=False)
    op.create_index(op.f('ix_chartings_parodontaux_id'), 'chartings_parodontaux', ['id'], unique=False)
    op.create_table('etats_dents_historique',
    sa.Column('date_constat', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dent_id', sa.UUID(), nullable=False),
    sa.Column('etat', sa.String(length=50), nullable=False),
    sa.Column('etat_precedent', sa.String(length=50), nullable=True),
    sa.Column('face', sa.String(length=20), nullable=True),
    sa.Column('consultation_id', sa.UUID(), nullable=True),
    sa.Column('praticien_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_etats_dents_historique_consultation_id_consultations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dent_id'], ['dents.id'], name=op.f('fk_etats_dents_historique_dent_id_dents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['praticien_id'], ['praticiens.id'], name=op.f('fk_etats_dents_historique_praticien_id_praticiens'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_etats_dents_historique'))
    )
    op.create_index(op.f('ix_etats_dents_historique_date_constat'), 'etats_dents_historique', ['date_constat'], unique=False)
    op.create_index(op.f('ix_etats_dents_historique_dent_id'), 'etats_dents_historique', ['dent_id'], unique=False)
    op.create_index(op.f('ix_etats_dents_historique_id'), 'etats_dents_historique', ['id'], unique=False)
    op.create_table('faces_dents',
    sa.Column('dent_id', sa.UUID(), nullable=False),
    sa.Column('face', sa.String(length=20), nullable=False),
    sa.Column('etat', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dent_id'], ['dents.id'], name=op.f('fk_faces_dents_dent_id_dents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faces_dents')),
    sa.UniqueConstraint('dent_id', 'face', name='uq_face_dent')
    )
    op.create_index(op.f('ix_faces_dents_dent_id'), 'faces_dents', ['dent_id'], unique=False)
    op.create_index(op.f('ix_faces_dents_id'), 'faces_dents', ['id'], unique=False)
    op.add_column('dents', sa.Column('numero_universal', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_dents_etat_actuel'), 'dents', ['etat_actuel'], unique=False)
    # Colonne NOT NULL sur une table déjà peuplée (RG11 : adulte = 32 dents,
    # enfant = 20 dents) : défaut explicite, sinon l'ALTER échoue.
    op.add_column(
        'odontogrammes',
        sa.Column('type', sa.String(length=20), nullable=False, server_default='ADULTE'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odontogrammes', 'type')
    op.drop_index(op.f('ix_dents_etat_actuel'), table_name='dents')
    op.drop_column('dents', 'numero_universal')
    op.drop_index(op.f('ix_faces_dents_id'), table_name='faces_dents')
    op.drop_index(op.f('ix_faces_dents_dent_id'), table_name='faces_dents')
    op.drop_table('faces_dents')
    op.drop_index(op.f('ix_etats_dents_historique_id'), table_name='etats_dents_historique')
    op.drop_index(op.f('ix_etats_dents_historique_dent_id'), table_name='etats_dents_historique')
    op.drop_index(op.f('ix_etats_dents_historique_date_constat'), table_name='etats_dents_historique')
    op.drop_table('etats_dents_historique')
    op.drop_index(op.f('ix_chartings_parodontaux_id'), table_name='chartings_parodontaux')
    op.drop_index(op.f('ix_chartings_parodontaux_dent_id'), table_name='chartings_parodontaux')
    op.drop_table('chartings_parodontaux')
    # ### end Alembic commands ###
