"""ordonnances_d1d

Revision ID: b76b4e21c632
Revises: 6e33b6d348d0
Create Date: 2026-10-02 22:44:48.598446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b76b4e21c632'
down_revision: Union[str, None] = '6e33b6d348d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicaments',
    sa.Column('nom_commercial', sa.String(length=150), nullable=False),
    sa.Column('dci', sa.String(length=150), nullable=False),
    sa.Column('forme', sa.String(length=50), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=True),
    sa.Column('classe_therapeutique', sa.String(length=50), nullable=True),
    sa.Column('contre_indications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('precautions', sa.Text(), nullable=True),
    sa.Column('posologie_adulte', sa.String(length=255), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medicaments'))
    )
    op.create_index(op.f('ix_medicaments_classe_therapeutique'), 'medicaments', ['classe_therapeutique'], unique=False)
    op.create_index(op.f('ix_medicaments_dci'), 'medicaments', ['dci'], unique=False)
    op.create_index(op.f('ix_medicaments_id'), 'medicaments', ['id'], unique=False)
    op.create_index(op.f('ix_medicaments_nom_commercial'), 'medicaments', ['nom_commercial'], unique=False)
    op.create_table('prescriptions',
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=False),
    sa.Column('praticien_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('date_ordonnance', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes_generales', sa.Text(), nullable=True),
    sa.Column('signe', sa.Boolean(), nullable=False),
    sa.Column('date_signature', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alertes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_prescriptions_consultation_id_consultations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_prescriptions_patient_id_patients')),
    sa.ForeignKeyConstraint(['praticien_id'], ['praticiens.id'], name=op.f('fk_prescriptions_praticien_id_praticiens')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescriptions'))
    )
    op.create_index(op.f('ix_prescriptions_consultation_id'), 'prescriptions', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_id'), 'prescriptions', ['id'], unique=False)
    op.create_index(op.f('ix_prescriptions_numero'), 'prescriptions', ['numero'], unique=True)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_table('lignes_prescription',
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('medicament_id', sa.UUID(), nullable=True),
    sa.Column('medicament_texte', sa.String(length=255), nullable=True),
    sa.Column('posologie', sa.String(length=255), nullable=False),
    sa.Column('duree', sa.String(length=100), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('justification_precaution', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['medicament_id'], ['medicaments.id'], name=op.f('fk_lignes_prescription_medicament_id_medicaments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('fk_lignes_prescription_prescription_id_prescriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lignes_prescription'))
    )
    op.create_index(op.f('ix_lignes_prescription_id'), 'lignes_prescription', ['id'], unique=False)
    op.create_index(op.f('ix_lignes_prescription_prescription_id'), 'lignes_prescription', ['prescription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lignes_prescription_prescription_id'), table_name='lignes_prescription')
    op.drop_index(op.f('ix_lignes_prescription_id'), table_name='lignes_prescription')
    op.drop_table('lignes_prescription')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_numero'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_consultation_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_medicaments_nom_commercial'), table_name='medicaments')
    op.drop_index(op.f('ix_medicaments_id'), table_name='medicaments')
    op.drop_index(op.f('ix_medicaments_dci'), table_name='medicaments')
    op.drop_index(op.f('ix_medicaments_classe_therapeutique'), table_name='medicaments')
    op.drop_table('medicaments')
    # ### end Alembic commands ###
