"""rendez_vous_d2b

Revision ID: f4433b308196
Revises: 522fe4028976
Create Date: 2026-10-03 11:07:47.815230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4433b308196'
down_revision: Union[str, None] = '522fe4028976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # `btree_gist` fournit l'opérateur `=` pour les UUID dans un index GiST,
    # sans quoi la contrainte d'exclusion « même praticien » est impossible à
    # exprimer. Elle doit être créée AVANT les tables qui l'utilisent, et
    # Alembic ne la génère pas : d'où cette ligne manuelle.
    #
    # `IF NOT EXISTS` rend la révision idempotente sur une base déjà équipée.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rendez_vous',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('cabinet_id', sa.UUID(), nullable=False),
    sa.Column('praticien_id', sa.UUID(), nullable=False),
    sa.Column('debut', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motif', sa.String(length=255), nullable=False),
    # `create_type=False` : ce type a été créé par la révision
    # `consultations_actes`. Sans ce drapeau, Alembic le recrée et la migration
    # échoue sur « type motifconsultationenum already exists ».
    sa.Column('type_motif', postgresql.ENUM('DOULEUR', 'CONTROLE', 'URGENCE', 'ESTHETIQUE', 'SUIVI', 'PROTHESE', 'ORTHODONTIE', 'AUTRE', name='motifconsultationenum', create_type=False), nullable=False),
    sa.Column('statut', sa.Enum('PLANIFIE', 'CONFIRME', 'EN_SALLE_ATTENTE', 'EN_CONSULTATION', 'TERMINEE', 'ANNULE', 'ABSENT', name='statutrendezvousenum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('motif_annulation', sa.String(length=255), nullable=True),
    sa.Column('date_statut', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    postgresql.ExcludeConstraint((sa.column('praticien_id'), '='), (sa.text("tstzrange(debut, fin, '[)')"), '&&'), where=sa.text("statut NOT IN ('ANNULE', 'ABSENT')"), using='gist', name='ex_rendez_vous_praticien'),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], name=op.f('fk_rendez_vous_cabinet_id_cabinets')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_rendez_vous_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['praticien_id'], ['praticiens.id'], name=op.f('fk_rendez_vous_praticien_id_praticiens')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rendez_vous'))
    )
    op.create_index(op.f('ix_rendez_vous_cabinet_id'), 'rendez_vous', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_rendez_vous_debut'), 'rendez_vous', ['debut'], unique=False)
    op.create_index(op.f('ix_rendez_vous_fin'), 'rendez_vous', ['fin'], unique=False)
    op.create_index(op.f('ix_rendez_vous_id'), 'rendez_vous', ['id'], unique=False)
    op.create_index(op.f('ix_rendez_vous_patient_id'), 'rendez_vous', ['patient_id'], unique=False)
    op.create_index(op.f('ix_rendez_vous_praticien_id'), 'rendez_vous', ['praticien_id'], unique=False)
    op.create_index(op.f('ix_rendez_vous_statut'), 'rendez_vous', ['statut'], unique=False)
    op.create_table('creneaux_fauteuil',
    sa.Column('fauteuil_id', sa.UUID(), nullable=False),
    sa.Column('rendez_vous_id', sa.UUID(), nullable=True),
    sa.Column('debut', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motif', sa.Enum('RENDEZ_VOUS', 'MAINTENANCE', 'REPARATION', 'RESERVATION', name='motifblocagefauteuilenum'), nullable=False),
    sa.Column('motif_detail', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    postgresql.ExcludeConstraint((sa.column('fauteuil_id'), '='), (sa.text("tstzrange(debut, fin, '[)')"), '&&'), using='gist', name='ex_creneau_fauteuil'),
    sa.ForeignKeyConstraint(['fauteuil_id'], ['fauteuils.id'], name=op.f('fk_creneaux_fauteuil_fauteuil_id_fauteuils'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rendez_vous_id'], ['rendez_vous.id'], name=op.f('fk_creneaux_fauteuil_rendez_vous_id_rendez_vous'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creneaux_fauteuil'))
    )
    op.create_index(op.f('ix_creneaux_fauteuil_debut'), 'creneaux_fauteuil', ['debut'], unique=False)
    op.create_index(op.f('ix_creneaux_fauteuil_fauteuil_id'), 'creneaux_fauteuil', ['fauteuil_id'], unique=False)
    op.create_index(op.f('ix_creneaux_fauteuil_fin'), 'creneaux_fauteuil', ['fin'], unique=False)
    op.create_index(op.f('ix_creneaux_fauteuil_id'), 'creneaux_fauteuil', ['id'], unique=False)
    op.create_index(op.f('ix_creneaux_fauteuil_rendez_vous_id'), 'creneaux_fauteuil', ['rendez_vous_id'], unique=False)
    op.add_column('consultations', sa.Column('rendez_vous_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_consultations_rendez_vous_id'), 'consultations', ['rendez_vous_id'], unique=True)
    op.create_foreign_key(op.f('fk_consultations_rendez_vous_id_rendez_vous'), 'consultations', 'rendez_vous', ['rendez_vous_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_consultations_rendez_vous_id_rendez_vous'), 'consultations', type_='foreignkey')
    op.drop_index(op.f('ix_consultations_rendez_vous_id'), table_name='consultations')
    op.drop_column('consultations', 'rendez_vous_id')
    op.drop_index(op.f('ix_creneaux_fauteuil_rendez_vous_id'), table_name='creneaux_fauteuil')
    op.drop_index(op.f('ix_creneaux_fauteuil_id'), table_name='creneaux_fauteuil')
    op.drop_index(op.f('ix_creneaux_fauteuil_fin'), table_name='creneaux_fauteuil')
    op.drop_index(op.f('ix_creneaux_fauteuil_fauteuil_id'), table_name='creneaux_fauteuil')
    op.drop_index(op.f('ix_creneaux_fauteuil_debut'), table_name='creneaux_fauteuil')
    op.drop_table('creneaux_fauteuil')
    op.drop_index(op.f('ix_rendez_vous_statut'), table_name='rendez_vous')
    op.drop_index(op.f('ix_rendez_vous_praticien_id'), table_name='rendez_vous')
    op.drop_index(op.f('ix_rendez_vous_patient_id'), table_name='rendez_vous')
    op.drop_index(op.f('ix_rendez_vous_id'), table_name='rendez_vous')
    op.drop_index(op.f('ix_rendez_vous_fin'), table_name='rendez_vous')
    op.drop_index(op.f('ix_rendez_vous_debut'), table_name='rendez_vous')
    op.drop_index(op.f('ix_rendez_vous_cabinet_id'), table_name='rendez_vous')
    op.drop_table('rendez_vous')
    # `btree_gist` n'est PAS supprimée : elle peut servir d'autres contraintes,
    # et une extension partagée ne nous appartient pas.
    # ### end Alembic commands ###
