"""baseline_tenant_schema

Revision ID: f4fb61aa2d24
Revises: 
Create Date: 2026-09-13 22:55:28.910029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4fb61aa2d24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actes_nomenclature',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('libelle', sa.String(length=200), nullable=False),
    sa.Column('categorie', sa.String(length=100), nullable=False),
    sa.Column('tarif_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('duree_estimee_min', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actes_nomenclature'))
    )
    op.create_index(op.f('ix_actes_nomenclature_code'), 'actes_nomenclature', ['code'], unique=True)
    op.create_index(op.f('ix_actes_nomenclature_id'), 'actes_nomenclature', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_email', sa.String(length=150), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('cabinets',
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('horaires_ouverture', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cabinets'))
    )
    op.create_index(op.f('ix_cabinets_id'), 'cabinets', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('numero_dossier', sa.String(length=50), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=False),
    sa.Column('sexe', sa.Enum('M', 'F', 'AUTRE', name='sexeenum'), nullable=False),
    sa.Column('type_piece_identite', sa.Enum('CNI', 'PASSEPORT', 'PERMIS', 'AUTRE', name='typepieceidentiteenum'), nullable=True),
    sa.Column('numero_piece_identite', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('telephone_1', sa.String(length=30), nullable=False),
    sa.Column('telephone_2', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('profession', sa.String(length=100), nullable=True),
    sa.Column('employeur', sa.String(length=150), nullable=True),
    sa.Column('groupe_sanguin', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_nom'), 'patients', ['nom'], unique=False)
    op.create_index(op.f('ix_patients_numero_dossier'), 'patients', ['numero_dossier'], unique=True)
    op.create_index(op.f('ix_patients_prenom'), 'patients', ['prenom'], unique=False)
    op.create_index(op.f('ix_patients_telephone_1'), 'patients', ['telephone_1'], unique=False)
    op.create_table('permissions',
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('module', 'action', name='uq_permission_module_action')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('niveau_hierarchie', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('nom', name=op.f('uq_roles_nom'))
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('dossiers_medicaux',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('notes_confidentielles', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_dossiers_medicaux_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dossiers_medicaux')),
    sa.UniqueConstraint('patient_id', name=op.f('uq_dossiers_medicaux_patient_id'))
    )
    op.create_index(op.f('ix_dossiers_medicaux_id'), 'dossiers_medicaux', ['id'], unique=False)
    op.create_table('permission_roles',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_permission_roles_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_permission_roles_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission_roles'))
    )
    op.create_index(op.f('ix_permission_roles_id'), 'permission_roles', ['id'], unique=False)
    op.create_table('salles',
    sa.Column('cabinet_id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('etage', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], name=op.f('fk_salles_cabinet_id_cabinets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salles'))
    )
    op.create_index(op.f('ix_salles_id'), 'salles', ['id'], unique=False)
    op.create_table('utilisateurs',
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('deux_facteurs', sa.Boolean(), nullable=False),
    sa.Column('secret_2fa', sa.String(length=100), nullable=True),
    sa.Column('dernier_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_utilisateurs_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_utilisateurs'))
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateurs_id'), 'utilisateurs', ['id'], unique=False)
    op.create_table('antecedents_medicaux',
    sa.Column('dossier_medical_id', sa.UUID(), nullable=False),
    sa.Column('type_antecedent', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('en_cours', sa.Boolean(), nullable=False),
    sa.Column('traitement_associe', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dossier_medical_id'], ['dossiers_medicaux.id'], name=op.f('fk_antecedents_medicaux_dossier_medical_id_dossiers_medicaux'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_antecedents_medicaux'))
    )
    op.create_index(op.f('ix_antecedents_medicaux_id'), 'antecedents_medicaux', ['id'], unique=False)
    op.create_table('etats_generaux',
    sa.Column('dossier_medical_id', sa.UUID(), nullable=False),
    sa.Column('grossesse', sa.Boolean(), nullable=False),
    sa.Column('allaitement', sa.Boolean(), nullable=False),
    sa.Column('diabete', sa.Boolean(), nullable=False),
    sa.Column('hta', sa.Boolean(), nullable=False),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tabac', sa.Boolean(), nullable=False),
    sa.Column('alcool', sa.Boolean(), nullable=False),
    sa.Column('autres_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dossier_medical_id'], ['dossiers_medicaux.id'], name=op.f('fk_etats_generaux_dossier_medical_id_dossiers_medicaux'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_etats_generaux')),
    sa.UniqueConstraint('dossier_medical_id', name=op.f('uq_etats_generaux_dossier_medical_id'))
    )
    op.create_index(op.f('ix_etats_generaux_id'), 'etats_generaux', ['id'], unique=False)
    op.create_table('fauteuils',
    sa.Column('salle_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('equipements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['salle_id'], ['salles.id'], name=op.f('fk_fauteuils_salle_id_salles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fauteuils'))
    )
    op.create_index(op.f('ix_fauteuils_id'), 'fauteuils', ['id'], unique=False)
    op.create_table('odontogrammes',
    sa.Column('dossier_medical_id', sa.UUID(), nullable=False),
    sa.Column('systeme_notation', sa.String(length=20), nullable=False),
    sa.Column('snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dossier_medical_id'], ['dossiers_medicaux.id'], name=op.f('fk_odontogrammes_dossier_medical_id_dossiers_medicaux'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_odontogrammes')),
    sa.UniqueConstraint('dossier_medical_id', name=op.f('uq_odontogrammes_dossier_medical_id'))
    )
    op.create_index(op.f('ix_odontogrammes_id'), 'odontogrammes', ['id'], unique=False)
    op.create_table('praticiens',
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.String(length=50), nullable=False),
    sa.Column('specialite', sa.String(length=100), nullable=False),
    sa.Column('numero_ordre', sa.String(length=50), nullable=True),
    sa.Column('signature_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], name=op.f('fk_praticiens_utilisateur_id_utilisateurs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_praticiens')),
    sa.UniqueConstraint('numero_ordre', name=op.f('uq_praticiens_numero_ordre')),
    sa.UniqueConstraint('utilisateur_id', name=op.f('uq_praticiens_utilisateur_id'))
    )
    op.create_index(op.f('ix_praticiens_id'), 'praticiens', ['id'], unique=False)
    op.create_table('sessions_utilisateurs',
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('est_revoque', sa.Boolean(), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], name=op.f('fk_sessions_utilisateurs_utilisateur_id_utilisateurs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions_utilisateurs'))
    )
    op.create_index(op.f('ix_sessions_utilisateurs_id'), 'sessions_utilisateurs', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_utilisateurs_refresh_token'), 'sessions_utilisateurs', ['refresh_token'], unique=True)
    op.create_table('consultations',
    sa.Column('dossier_medical_id', sa.UUID(), nullable=False),
    sa.Column('praticien_id', sa.UUID(), nullable=False),
    sa.Column('cabinet_id', sa.UUID(), nullable=False),
    sa.Column('motif', sa.String(length=255), nullable=False),
    sa.Column('anamnese', sa.Text(), nullable=True),
    sa.Column('examen_endobuccal', sa.Text(), nullable=True),
    sa.Column('diagnostic_principal', sa.Text(), nullable=True),
    sa.Column('plan_traitement', sa.Text(), nullable=True),
    sa.Column('statut', sa.Enum('PLANIFIEE', 'EN_ATTENTE', 'EN_COURS', 'TERMINEE', 'ANNULEE', name='statutconsultationenum'), nullable=False),
    sa.Column('date_consultation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duree_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], name=op.f('fk_consultations_cabinet_id_cabinets')),
    sa.ForeignKeyConstraint(['dossier_medical_id'], ['dossiers_medicaux.id'], name=op.f('fk_consultations_dossier_medical_id_dossiers_medicaux')),
    sa.ForeignKeyConstraint(['praticien_id'], ['praticiens.id'], name=op.f('fk_consultations_praticien_id_praticiens')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultations'))
    )
    op.create_index(op.f('ix_consultations_id'), 'consultations', ['id'], unique=False)
    op.create_table('dents',
    sa.Column('odontogramme_id', sa.UUID(), nullable=False),
    sa.Column('numero_fdi', sa.Integer(), nullable=False),
    sa.Column('etat_actuel', sa.String(length=50), nullable=False),
    sa.Column('mobilite', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['odontogramme_id'], ['odontogrammes.id'], name=op.f('fk_dents_odontogramme_id_odontogrammes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dents')),
    sa.UniqueConstraint('odontogramme_id', 'numero_fdi', name='uq_dent_odontogramme_fdi')
    )
    op.create_index(op.f('ix_dents_id'), 'dents', ['id'], unique=False)
    op.create_index(op.f('ix_dents_numero_fdi'), 'dents', ['numero_fdi'], unique=False)
    op.create_table('actes_realises',
    sa.Column('consultation_id', sa.UUID(), nullable=False),
    sa.Column('acte_id', sa.UUID(), nullable=False),
    sa.Column('dent_numero', sa.Integer(), nullable=True),
    sa.Column('face', sa.String(length=20), nullable=True),
    sa.Column('tarif_applique', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acte_id'], ['actes_nomenclature.id'], name=op.f('fk_actes_realises_acte_id_actes_nomenclature')),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_actes_realises_consultation_id_consultations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actes_realises'))
    )
    op.create_index(op.f('ix_actes_realises_id'), 'actes_realises', ['id'], unique=False)
    op.create_table('factures',
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('cabinet_id', sa.UUID(), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=True),
    sa.Column('montant_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('montant_tva', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('montant_paye', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('montant_restant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('statut', sa.Enum('BROUILLON', 'EMISE', 'PARTIELLEMENT_PAYEE', 'PAYEE', 'ANNULEE', name='statutfactureenum'), nullable=False),
    sa.Column('date_emission', sa.Date(), nullable=False),
    sa.Column('date_echeance', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], name=op.f('fk_factures_cabinet_id_cabinets')),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_factures_consultation_id_consultations')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_factures_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_factures'))
    )
    op.create_index(op.f('ix_factures_id'), 'factures', ['id'], unique=False)
    op.create_index(op.f('ix_factures_numero'), 'factures', ['numero'], unique=True)
    op.create_table('lignes_facture',
    sa.Column('facture_id', sa.UUID(), nullable=False),
    sa.Column('acte_realise_id', sa.UUID(), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['acte_realise_id'], ['actes_realises.id'], name=op.f('fk_lignes_facture_acte_realise_id_actes_realises')),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], name=op.f('fk_lignes_facture_facture_id_factures'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lignes_facture'))
    )
    op.create_index(op.f('ix_lignes_facture_id'), 'lignes_facture', ['id'], unique=False)
    op.create_table('paiements',
    sa.Column('facture_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mode', sa.Enum('ESPECES', 'CARTE_BANCAIRE', 'CHEQUE', 'VIREMENT', 'MOBILE_MONEY', 'ASSURANCE', name='modepaiementenum'), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('recu_numero', sa.String(length=50), nullable=False),
    sa.Column('date_paiement', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], name=op.f('fk_paiements_facture_id_factures'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_paiements_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paiements'))
    )
    op.create_index(op.f('ix_paiements_id'), 'paiements', ['id'], unique=False)
    op.create_index(op.f('ix_paiements_recu_numero'), 'paiements', ['recu_numero'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paiements_recu_numero'), table_name='paiements')
    op.drop_index(op.f('ix_paiements_id'), table_name='paiements')
    op.drop_table('paiements')
    op.drop_index(op.f('ix_lignes_facture_id'), table_name='lignes_facture')
    op.drop_table('lignes_facture')
    op.drop_index(op.f('ix_factures_numero'), table_name='factures')
    op.drop_index(op.f('ix_factures_id'), table_name='factures')
    op.drop_table('factures')
    op.drop_index(op.f('ix_actes_realises_id'), table_name='actes_realises')
    op.drop_table('actes_realises')
    op.drop_index(op.f('ix_dents_numero_fdi'), table_name='dents')
    op.drop_index(op.f('ix_dents_id'), table_name='dents')
    op.drop_table('dents')
    op.drop_index(op.f('ix_consultations_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_sessions_utilisateurs_refresh_token'), table_name='sessions_utilisateurs')
    op.drop_index(op.f('ix_sessions_utilisateurs_id'), table_name='sessions_utilisateurs')
    op.drop_table('sessions_utilisateurs')
    op.drop_index(op.f('ix_praticiens_id'), table_name='praticiens')
    op.drop_table('praticiens')
    op.drop_index(op.f('ix_odontogrammes_id'), table_name='odontogrammes')
    op.drop_table('odontogrammes')
    op.drop_index(op.f('ix_fauteuils_id'), table_name='fauteuils')
    op.drop_table('fauteuils')
    op.drop_index(op.f('ix_etats_generaux_id'), table_name='etats_generaux')
    op.drop_table('etats_generaux')
    op.drop_index(op.f('ix_antecedents_medicaux_id'), table_name='antecedents_medicaux')
    op.drop_table('antecedents_medicaux')
    op.drop_index(op.f('ix_utilisateurs_id'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_index(op.f('ix_salles_id'), table_name='salles')
    op.drop_table('salles')
    op.drop_index(op.f('ix_permission_roles_id'), table_name='permission_roles')
    op.drop_table('permission_roles')
    op.drop_index(op.f('ix_dossiers_medicaux_id'), table_name='dossiers_medicaux')
    op.drop_table('dossiers_medicaux')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_patients_telephone_1'), table_name='patients')
    op.drop_index(op.f('ix_patients_prenom'), table_name='patients')
    op.drop_index(op.f('ix_patients_numero_dossier'), table_name='patients')
    op.drop_index(op.f('ix_patients_nom'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_cabinets_id'), table_name='cabinets')
    op.drop_table('cabinets')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_actes_nomenclature_id'), table_name='actes_nomenclature')
    op.drop_index(op.f('ix_actes_nomenclature_code'), table_name='actes_nomenclature')
    op.drop_table('actes_nomenclature')
    # ### end Alembic commands ###
