"""patients_dossier_medical

Revision ID: f81d897fd9db
Revises: f4fb61aa2d24
Create Date: 2026-10-01 18:50:49.230837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f81d897fd9db'
down_revision: Union[str, None] = 'f4fb61aa2d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compteurs',
    sa.Column('compteur', sa.String(length=50), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('valeur', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('compteur', 'annee', name=op.f('pk_compteurs'))
    )
    op.add_column('antecedents_medicaux', sa.Column('date_survenue', sa.Date(), nullable=True))
    op.add_column('antecedents_medicaux', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('etats_generaux', sa.Column('grossesse_terme', sa.String(length=50), nullable=True))
    op.add_column('etats_generaux', sa.Column('diabete_type', sa.String(length=50), nullable=True))
    op.add_column('etats_generaux', sa.Column('examens_complementaires', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etats_generaux', 'examens_complementaires')
    op.drop_column('etats_generaux', 'diabete_type')
    op.drop_column('etats_generaux', 'grossesse_terme')
    op.drop_column('antecedents_medicaux', 'notes')
    op.drop_column('antecedents_medicaux', 'date_survenue')
    op.drop_table('compteurs')
    # ### end Alembic commands ###
