"""baseline plateforme

Revision ID: bc633ae8cd75
Revises: 
Create Date: 2026-10-04 20:52:27.554275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc633ae8cd75'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acces_support',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('agent_email', sa.String(length=150), nullable=False),
    sa.Column('motif', sa.Text(), nullable=False),
    sa.Column('ticket', sa.String(length=80), nullable=True),
    sa.Column('lecture_seule', sa.Boolean(), nullable=False),
    sa.Column('statut', sa.Enum('ACTIF', 'EXPIRE', 'REVOQUE', name='statut_acces_support'), nullable=False),
    sa.Column('expire_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoque_par', sa.UUID(), nullable=True),
    sa.Column('revoque_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motif_revoque', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('admin_notifie', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acces_support'))
    )
    op.create_index(op.f('ix_acces_support_agent_email'), 'acces_support', ['agent_email'], unique=False)
    op.create_index(op.f('ix_acces_support_agent_id'), 'acces_support', ['agent_id'], unique=False)
    op.create_index(op.f('ix_acces_support_expire_le'), 'acces_support', ['expire_le'], unique=False)
    op.create_index(op.f('ix_acces_support_id'), 'acces_support', ['id'], unique=False)
    op.create_index(op.f('ix_acces_support_statut'), 'acces_support', ['statut'], unique=False)
    op.create_index(op.f('ix_acces_support_tenant_id'), 'acces_support', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_acces_support_ticket'), 'acces_support', ['ticket'], unique=False)
    op.create_table('annonces',
    sa.Column('titre', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type_annonce', sa.Enum('INFO', 'MAINTENANCE', 'NOUVEAUTE', 'ALERTE', name='type_annonce'), nullable=False),
    sa.Column('debut', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('plans_cibles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tenants_cibles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cree_par', sa.String(length=150), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annonces'))
    )
    op.create_index(op.f('ix_annonces_active'), 'annonces', ['active'], unique=False)
    op.create_index(op.f('ix_annonces_debut'), 'annonces', ['debut'], unique=False)
    op.create_index(op.f('ix_annonces_fin'), 'annonces', ['fin'], unique=False)
    op.create_index(op.f('ix_annonces_id'), 'annonces', ['id'], unique=False)
    op.create_table('exports_tenant',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('type_export', sa.String(length=30), nullable=False),
    sa.Column('statut', sa.Enum('EN_COURS', 'TERMINE', 'ECHEC', 'SUPPRIME', name='statut_export'), nullable=False),
    sa.Column('chemin_chiffre', sa.Text(), nullable=True),
    sa.Column('taille_octets', sa.Integer(), nullable=True),
    sa.Column('expire_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('demande_par', sa.String(length=150), nullable=False),
    sa.Column('motif', sa.Text(), nullable=False),
    sa.Column('erreur', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exports_tenant'))
    )
    op.create_index(op.f('ix_exports_tenant_id'), 'exports_tenant', ['id'], unique=False)
    op.create_index(op.f('ix_exports_tenant_tenant_id'), 'exports_tenant', ['tenant_id'], unique=False)
    op.create_table('gabarits_semis',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('type_gabarit', sa.Enum('ACTES', 'MEDICAMENTS', 'FORMULAIRE', 'PARAMETRES', 'ROLES', name='type_gabarit'), nullable=False),
    sa.Column('libelle', sa.String(length=120), nullable=False),
    sa.Column('contenu', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('cree_par', sa.String(length=150), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gabarits_semis')),
    sa.UniqueConstraint('code', 'version', name='uq_gabarit_code_version')
    )
    op.create_index(op.f('ix_gabarits_semis_actif'), 'gabarits_semis', ['actif'], unique=False)
    op.create_index(op.f('ix_gabarits_semis_code'), 'gabarits_semis', ['code'], unique=False)
    op.create_index(op.f('ix_gabarits_semis_id'), 'gabarits_semis', ['id'], unique=False)
    op.create_index(op.f('ix_gabarits_semis_type_gabarit'), 'gabarits_semis', ['type_gabarit'], unique=False)
    op.create_table('inscriptions_onboarding',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('plan_code', sa.String(length=40), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE_VERIFICATION', 'VERIFIE', 'ACTIF', 'REJETE', 'ERREUR', name='statut_inscription'), nullable=False),
    sa.Column('email_verifie', sa.Boolean(), nullable=False),
    sa.Column('telephone_verifie', sa.Boolean(), nullable=False),
    sa.Column('erreur', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('verifie_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inscriptions_onboarding'))
    )
    op.create_index(op.f('ix_inscriptions_onboarding_email'), 'inscriptions_onboarding', ['email'], unique=False)
    op.create_index(op.f('ix_inscriptions_onboarding_id'), 'inscriptions_onboarding', ['id'], unique=False)
    op.create_index(op.f('ix_inscriptions_onboarding_statut'), 'inscriptions_onboarding', ['statut'], unique=False)
    op.create_index(op.f('ix_inscriptions_onboarding_tenant_id'), 'inscriptions_onboarding', ['tenant_id'], unique=False)
    op.create_table('jetons_usage_unique',
    sa.Column('usage', sa.Enum('VERIFICATION_EMAIL', 'VERIFICATION_TELEPHONE', 'INVITATION_ADMIN', 'REINITIALISATION_ACCES', 'REPLACEMENT_ADMIN', name='usage_jeton'), nullable=False),
    sa.Column('hash_jeton', sa.String(length=64), nullable=False),
    sa.Column('cible_type', sa.String(length=40), nullable=False),
    sa.Column('cible_id', sa.String(length=120), nullable=False),
    sa.Column('expire_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('utilise', sa.Boolean(), nullable=False),
    sa.Column('utilise_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.String(length=150), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jetons_usage_unique'))
    )
    op.create_index(op.f('ix_jetons_usage_unique_cible_id'), 'jetons_usage_unique', ['cible_id'], unique=False)
    op.create_index(op.f('ix_jetons_usage_unique_expire_le'), 'jetons_usage_unique', ['expire_le'], unique=False)
    op.create_index(op.f('ix_jetons_usage_unique_hash_jeton'), 'jetons_usage_unique', ['hash_jeton'], unique=True)
    op.create_index(op.f('ix_jetons_usage_unique_id'), 'jetons_usage_unique', ['id'], unique=False)
    op.create_index(op.f('ix_jetons_usage_unique_usage'), 'jetons_usage_unique', ['usage'], unique=False)
    op.create_table('journal_audit_plateforme',
    sa.Column('horodatage', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acteur_id', sa.UUID(), nullable=True),
    sa.Column('acteur_email', sa.String(length=150), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('type_cible', sa.String(length=40), nullable=False),
    sa.Column('cible_id', sa.String(length=120), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('avant', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('apres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_audit_plateforme'))
    )
    op.create_index(op.f('ix_journal_audit_plateforme_acteur_email'), 'journal_audit_plateforme', ['acteur_email'], unique=False)
    op.create_index(op.f('ix_journal_audit_plateforme_acteur_id'), 'journal_audit_plateforme', ['acteur_id'], unique=False)
    op.create_index(op.f('ix_journal_audit_plateforme_action'), 'journal_audit_plateforme', ['action'], unique=False)
    op.create_index(op.f('ix_journal_audit_plateforme_cible_id'), 'journal_audit_plateforme', ['cible_id'], unique=False)
    op.create_index(op.f('ix_journal_audit_plateforme_horodatage'), 'journal_audit_plateforme', ['horodatage'], unique=False)
    op.create_index(op.f('ix_journal_audit_plateforme_id'), 'journal_audit_plateforme', ['id'], unique=False)
    op.create_index(op.f('ix_journal_audit_plateforme_request_id'), 'journal_audit_plateforme', ['request_id'], unique=False)
    op.create_index(op.f('ix_journal_audit_plateforme_tenant_id'), 'journal_audit_plateforme', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_journal_audit_plateforme_type_cible'), 'journal_audit_plateforme', ['type_cible'], unique=False)
    op.create_table('migrations_tenant',
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tenant_nom', sa.String(length=150), nullable=True),
    sa.Column('revision_avant', sa.String(length=40), nullable=True),
    sa.Column('revision_apres', sa.String(length=40), nullable=True),
    sa.Column('statut', sa.Enum('EN_COURS', 'SUCCES', 'ECHEC', 'IGNORE', name='statut_migration_tenant'), nullable=False),
    sa.Column('duree_ms', sa.Integer(), nullable=True),
    sa.Column('erreur', sa.Text(), nullable=True),
    sa.Column('lance_par', sa.String(length=150), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_migrations_tenant'))
    )
    op.create_index(op.f('ix_migrations_tenant_id'), 'migrations_tenant', ['id'], unique=False)
    op.create_index(op.f('ix_migrations_tenant_started_at'), 'migrations_tenant', ['started_at'], unique=False)
    op.create_index(op.f('ix_migrations_tenant_statut'), 'migrations_tenant', ['statut'], unique=False)
    op.create_index(op.f('ix_migrations_tenant_tenant_id'), 'migrations_tenant', ['tenant_id'], unique=False)
    op.create_table('permissions_plateforme',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('ressource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('sensible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions_plateforme'))
    )
    op.create_index(op.f('ix_permissions_plateforme_action'), 'permissions_plateforme', ['action'], unique=False)
    op.create_index(op.f('ix_permissions_plateforme_code'), 'permissions_plateforme', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_plateforme_id'), 'permissions_plateforme', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_plateforme_ressource'), 'permissions_plateforme', ['ressource'], unique=False)
    op.create_table('plans',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prix', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('periodicite', sa.Enum('MENSUEL', 'ANNUEL', 'GRATUIT', name='periode_facturation'), nullable=False),
    sa.Column('devise', sa.String(length=3), nullable=False),
    sa.Column('quotas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('plan_defaut', sa.Boolean(), nullable=False),
    sa.Column('jours_essai', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans'))
    )
    op.create_index(op.f('ix_plans_code'), 'plans', ['code'], unique=True)
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_plan_defaut'), 'plans', ['plan_defaut'], unique=False)
    op.create_table('roles_plateforme',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('libelle', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('niveau_hierarchie', sa.SmallInteger(), nullable=False),
    sa.Column('systeme', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles_plateforme'))
    )
    op.create_index(op.f('ix_roles_plateforme_code'), 'roles_plateforme', ['code'], unique=True)
    op.create_index(op.f('ix_roles_plateforme_id'), 'roles_plateforme', ['id'], unique=False)
    op.create_table('stats_tenant',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('jour', sa.Date(), nullable=False),
    sa.Column('utilisateurs_actifs', sa.Integer(), nullable=False),
    sa.Column('sites', sa.Integer(), nullable=False),
    sa.Column('praticiens', sa.Integer(), nullable=False),
    sa.Column('patients', sa.Integer(), nullable=False),
    sa.Column('rendez_vous_periode', sa.Integer(), nullable=False),
    sa.Column('stockage_octets', sa.Integer(), nullable=False),
    sa.Column('sms_envoyes', sa.Integer(), nullable=False),
    sa.Column('factures_creees', sa.Integer(), nullable=False),
    sa.Column('derniere_activite', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calcule_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stats_tenant')),
    sa.UniqueConstraint('tenant_id', 'jour', name='uq_stats_tenant_jour')
    )
    op.create_index(op.f('ix_stats_tenant_id'), 'stats_tenant', ['id'], unique=False)
    op.create_index(op.f('ix_stats_tenant_jour'), 'stats_tenant', ['jour'], unique=False)
    op.create_index(op.f('ix_stats_tenant_tenant_id'), 'stats_tenant', ['tenant_id'], unique=False)
    op.create_table('statuts_tenant_historique',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('statut_precedent', sa.String(length=20), nullable=False),
    sa.Column('statut_nouveau', sa.String(length=20), nullable=False),
    sa.Column('motif', sa.Text(), nullable=False),
    sa.Column('auteur_id', sa.UUID(), nullable=True),
    sa.Column('auteur_email', sa.String(length=150), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statuts_tenant_historique'))
    )
    op.create_index(op.f('ix_statuts_tenant_historique_id'), 'statuts_tenant_historique', ['id'], unique=False)
    op.create_index(op.f('ix_statuts_tenant_historique_tenant_id'), 'statuts_tenant_historique', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_statuts_tenant_historique_timestamp'), 'statuts_tenant_historique', ['timestamp'], unique=False)
    op.create_table('tenants_plateforme',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('statut_metier', sa.Enum('ESSAI', 'ACTIF', 'SUSPENDU', 'RESILIE', name='statut_tenant'), nullable=False),
    sa.Column('archivable', sa.Boolean(), nullable=False),
    sa.Column('motif_statut', sa.Text(), nullable=True),
    sa.Column('date_debut_essai', sa.Date(), nullable=True),
    sa.Column('date_fin_essai', sa.Date(), nullable=True),
    sa.Column('date_activation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_suspension', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_resiliation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('langue', sa.String(length=5), nullable=False),
    sa.Column('fuseau_horaire', sa.String(length=50), nullable=False),
    sa.Column('devise', sa.String(length=3), nullable=False),
    sa.Column('pays', sa.String(length=100), nullable=False),
    sa.Column('admin_email', sa.String(length=150), nullable=True),
    sa.Column('admin_acces_reinitialise_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants_plateforme'))
    )
    op.create_index(op.f('ix_tenants_plateforme_archivable'), 'tenants_plateforme', ['archivable'], unique=False)
    op.create_index(op.f('ix_tenants_plateforme_date_fin_essai'), 'tenants_plateforme', ['date_fin_essai'], unique=False)
    op.create_index(op.f('ix_tenants_plateforme_id'), 'tenants_plateforme', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_plateforme_statut_metier'), 'tenants_plateforme', ['statut_metier'], unique=False)
    op.create_index(op.f('ix_tenants_plateforme_tenant_id'), 'tenants_plateforme', ['tenant_id'], unique=True)
    op.create_table('utilisateurs_plateforme',
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('prenom', sa.String(length=80), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('statut', sa.Enum('ACTIF', 'DESACTIF', 'VERROUILLE', name='statut_utilisateur_plateforme'), nullable=False),
    sa.Column('motif_desactivation', sa.Text(), nullable=True),
    sa.Column('deux_facteurs_actif', sa.Boolean(), nullable=False),
    sa.Column('secret_2fa_chiffre', sa.Text(), nullable=True),
    sa.Column('deux_facteurs_confirme_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tentatives_echouees', sa.Integer(), nullable=False),
    sa.Column('verrouille_jusqua', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dernier_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_utilisateurs_plateforme'))
    )
    op.create_index(op.f('ix_utilisateurs_plateforme_email'), 'utilisateurs_plateforme', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateurs_plateforme_id'), 'utilisateurs_plateforme', ['id'], unique=False)
    op.create_index(op.f('ix_utilisateurs_plateforme_statut'), 'utilisateurs_plateforme', ['statut'], unique=False)
    op.create_table('abonnements',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('statut', sa.Enum('ESSAI', 'ACTIF', 'SUSPENDU', 'EXPIRE', 'RESILIE', name='statut_abonnement'), nullable=False),
    sa.Column('plan_fige', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('date_debut', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_debut_essai', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_fin_essai', sa.DateTime(timezone=True), nullable=True),
    sa.Column('renouvellement_auto', sa.Boolean(), nullable=False),
    sa.Column('numero_abonnement', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_abonnements_plan_id_plans'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_abonnements')),
    sa.UniqueConstraint('numero_abonnement', name=op.f('uq_abonnements_numero_abonnement'))
    )
    op.create_index(op.f('ix_abonnements_date_fin_essai'), 'abonnements', ['date_fin_essai'], unique=False)
    op.create_index(op.f('ix_abonnements_id'), 'abonnements', ['id'], unique=False)
    op.create_index(op.f('ix_abonnements_plan_id'), 'abonnements', ['plan_id'], unique=False)
    op.create_index(op.f('ix_abonnements_statut'), 'abonnements', ['statut'], unique=False)
    op.create_index(op.f('ix_abonnements_tenant_id'), 'abonnements', ['tenant_id'], unique=True)
    op.create_table('plan_revisions',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('instantane', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.Column('auteur', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_revisions_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_revisions'))
    )
    op.create_index(op.f('ix_plan_revisions_created_at'), 'plan_revisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_plan_revisions_id'), 'plan_revisions', ['id'], unique=False)
    op.create_index(op.f('ix_plan_revisions_plan_id'), 'plan_revisions', ['plan_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions_plateforme.id'], name=op.f('fk_role_permissions_permission_id_permissions_plateforme'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles_plateforme.id'], name=op.f('fk_role_permissions_role_id_roles_plateforme'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('sessions_plateforme',
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('est_revoque', sa.Boolean(), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('derniere_activite', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs_plateforme.id'], name=op.f('fk_sessions_plateforme_utilisateur_id_utilisateurs_plateforme'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions_plateforme'))
    )
    op.create_index(op.f('ix_sessions_plateforme_id'), 'sessions_plateforme', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_plateforme_jti'), 'sessions_plateforme', ['jti'], unique=True)
    op.create_index(op.f('ix_sessions_plateforme_refresh_token_hash'), 'sessions_plateforme', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_plateforme_utilisateur_id'), 'sessions_plateforme', ['utilisateur_id'], unique=False)
    op.create_table('utilisateur_roles',
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles_plateforme.id'], name=op.f('fk_utilisateur_roles_role_id_roles_plateforme'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs_plateforme.id'], name=op.f('fk_utilisateur_roles_utilisateur_id_utilisateurs_plateforme'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('utilisateur_id', 'role_id', name=op.f('pk_utilisateur_roles'))
    )
    op.create_table('abonnement_historique',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('abonnement_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('avant', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('apres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.Column('auteur', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['abonnement_id'], ['abonnements.id'], name=op.f('fk_abonnement_historique_abonnement_id_abonnements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_abonnement_historique'))
    )
    op.create_index(op.f('ix_abonnement_historique_abonnement_id'), 'abonnement_historique', ['abonnement_id'], unique=False)
    op.create_index(op.f('ix_abonnement_historique_created_at'), 'abonnement_historique', ['created_at'], unique=False)
    op.create_index(op.f('ix_abonnement_historique_id'), 'abonnement_historique', ['id'], unique=False)
    op.create_index(op.f('ix_abonnement_historique_tenant_id'), 'abonnement_historique', ['tenant_id'], unique=False)
    op.create_table('factures_plateforme',
    sa.Column('numero', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('abonnement_id', sa.UUID(), nullable=True),
    sa.Column('lignes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('devise', sa.String(length=3), nullable=False),
    sa.Column('statut', sa.Enum('BROUILLON', 'EMISE', 'PAYEE', 'EN_RETARD', 'ANNULEE', name='statut_facture_plateforme'), nullable=False),
    sa.Column('periode_debut', sa.Date(), nullable=True),
    sa.Column('periode_fin', sa.Date(), nullable=True),
    sa.Column('date_emission', sa.Date(), nullable=True),
    sa.Column('date_echeance', sa.Date(), nullable=True),
    sa.Column('date_paiement', sa.Date(), nullable=True),
    sa.Column('moyen_paiement', sa.String(length=40), nullable=True),
    sa.Column('reference_externe', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['abonnement_id'], ['abonnements.id'], name=op.f('fk_factures_plateforme_abonnement_id_abonnements'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_factures_plateforme'))
    )
    op.create_index(op.f('ix_factures_plateforme_date_echeance'), 'factures_plateforme', ['date_echeance'], unique=False)
    op.create_index(op.f('ix_factures_plateforme_id'), 'factures_plateforme', ['id'], unique=False)
    op.create_index(op.f('ix_factures_plateforme_numero'), 'factures_plateforme', ['numero'], unique=True)
    op.create_index(op.f('ix_factures_plateforme_reference_externe'), 'factures_plateforme', ['reference_externe'], unique=False)
    op.create_index(op.f('ix_factures_plateforme_statut'), 'factures_plateforme', ['statut'], unique=False)
    op.create_index(op.f('ix_factures_plateforme_tenant_id'), 'factures_plateforme', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # Immuabilité du journal d'audit plateforme (Phase E.2)
    # ------------------------------------------------------------------
    # Le journal est APPEND-ONLY. Aucune route ne permet de le modifier ou de le
    # supprimer, mais « aucune route ne le fait » n'est pas une garantie : une
    # requête à la main, un script de reprise ou un futur `session.delete()`
    # contourneraient la discipline de code. Le déclencheur ci-dessous rend la
    # garantie structurelle : PostgreSQL refuse l'écriture, quel que soit
    # l'appelant et quel que soit le rôle SQL.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION plateforme_journal_append_only()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'journal_audit_plateforme est append-only : % sur % est interdit',
                TG_OP, TG_TABLE_NAME
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER journal_audit_plateforme_append_only
        BEFORE UPDATE OR DELETE ON journal_audit_plateforme
        FOR EACH ROW EXECUTE FUNCTION plateforme_journal_append_only();
        """
    )
    # RétENTION : le journal n'est jamais purgé automatiquement. Une purge
    # éventuelle est une décision explicite de l'éditeur, hors de ce migration.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_factures_plateforme_tenant_id'), table_name='factures_plateforme')
    op.drop_index(op.f('ix_factures_plateforme_statut'), table_name='factures_plateforme')
    op.drop_index(op.f('ix_factures_plateforme_reference_externe'), table_name='factures_plateforme')
    op.drop_index(op.f('ix_factures_plateforme_numero'), table_name='factures_plateforme')
    op.drop_index(op.f('ix_factures_plateforme_id'), table_name='factures_plateforme')
    op.drop_index(op.f('ix_factures_plateforme_date_echeance'), table_name='factures_plateforme')
    op.drop_table('factures_plateforme')
    op.drop_index(op.f('ix_abonnement_historique_tenant_id'), table_name='abonnement_historique')
    op.drop_index(op.f('ix_abonnement_historique_id'), table_name='abonnement_historique')
    op.drop_index(op.f('ix_abonnement_historique_created_at'), table_name='abonnement_historique')
    op.drop_index(op.f('ix_abonnement_historique_abonnement_id'), table_name='abonnement_historique')
    op.drop_table('abonnement_historique')
    op.drop_table('utilisateur_roles')
    op.drop_index(op.f('ix_sessions_plateforme_utilisateur_id'), table_name='sessions_plateforme')
    op.drop_index(op.f('ix_sessions_plateforme_refresh_token_hash'), table_name='sessions_plateforme')
    op.drop_index(op.f('ix_sessions_plateforme_jti'), table_name='sessions_plateforme')
    op.drop_index(op.f('ix_sessions_plateforme_id'), table_name='sessions_plateforme')
    op.drop_table('sessions_plateforme')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_plan_revisions_plan_id'), table_name='plan_revisions')
    op.drop_index(op.f('ix_plan_revisions_id'), table_name='plan_revisions')
    op.drop_index(op.f('ix_plan_revisions_created_at'), table_name='plan_revisions')
    op.drop_table('plan_revisions')
    op.drop_index(op.f('ix_abonnements_tenant_id'), table_name='abonnements')
    op.drop_index(op.f('ix_abonnements_statut'), table_name='abonnements')
    op.drop_index(op.f('ix_abonnements_plan_id'), table_name='abonnements')
    op.drop_index(op.f('ix_abonnements_id'), table_name='abonnements')
    op.drop_index(op.f('ix_abonnements_date_fin_essai'), table_name='abonnements')
    op.drop_table('abonnements')
    op.drop_index(op.f('ix_utilisateurs_plateforme_statut'), table_name='utilisateurs_plateforme')
    op.drop_index(op.f('ix_utilisateurs_plateforme_id'), table_name='utilisateurs_plateforme')
    op.drop_index(op.f('ix_utilisateurs_plateforme_email'), table_name='utilisateurs_plateforme')
    op.drop_table('utilisateurs_plateforme')
    op.drop_index(op.f('ix_tenants_plateforme_tenant_id'), table_name='tenants_plateforme')
    op.drop_index(op.f('ix_tenants_plateforme_statut_metier'), table_name='tenants_plateforme')
    op.drop_index(op.f('ix_tenants_plateforme_id'), table_name='tenants_plateforme')
    op.drop_index(op.f('ix_tenants_plateforme_date_fin_essai'), table_name='tenants_plateforme')
    op.drop_index(op.f('ix_tenants_plateforme_archivable'), table_name='tenants_plateforme')
    op.drop_table('tenants_plateforme')
    op.drop_index(op.f('ix_statuts_tenant_historique_timestamp'), table_name='statuts_tenant_historique')
    op.drop_index(op.f('ix_statuts_tenant_historique_tenant_id'), table_name='statuts_tenant_historique')
    op.drop_index(op.f('ix_statuts_tenant_historique_id'), table_name='statuts_tenant_historique')
    op.drop_table('statuts_tenant_historique')
    op.drop_index(op.f('ix_stats_tenant_tenant_id'), table_name='stats_tenant')
    op.drop_index(op.f('ix_stats_tenant_jour'), table_name='stats_tenant')
    op.drop_index(op.f('ix_stats_tenant_id'), table_name='stats_tenant')
    op.drop_table('stats_tenant')
    op.drop_index(op.f('ix_roles_plateforme_id'), table_name='roles_plateforme')
    op.drop_index(op.f('ix_roles_plateforme_code'), table_name='roles_plateforme')
    op.drop_table('roles_plateforme')
    op.drop_index(op.f('ix_plans_plan_defaut'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_code'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_permissions_plateforme_ressource'), table_name='permissions_plateforme')
    op.drop_index(op.f('ix_permissions_plateforme_id'), table_name='permissions_plateforme')
    op.drop_index(op.f('ix_permissions_plateforme_code'), table_name='permissions_plateforme')
    op.drop_index(op.f('ix_permissions_plateforme_action'), table_name='permissions_plateforme')
    op.drop_table('permissions_plateforme')
    op.drop_index(op.f('ix_migrations_tenant_tenant_id'), table_name='migrations_tenant')
    op.drop_index(op.f('ix_migrations_tenant_statut'), table_name='migrations_tenant')
    op.drop_index(op.f('ix_migrations_tenant_started_at'), table_name='migrations_tenant')
    op.drop_index(op.f('ix_migrations_tenant_id'), table_name='migrations_tenant')
    op.drop_table('migrations_tenant')
    op.drop_index(op.f('ix_journal_audit_plateforme_type_cible'), table_name='journal_audit_plateforme')
    op.drop_index(op.f('ix_journal_audit_plateforme_tenant_id'), table_name='journal_audit_plateforme')
    op.drop_index(op.f('ix_journal_audit_plateforme_request_id'), table_name='journal_audit_plateforme')
    op.drop_index(op.f('ix_journal_audit_plateforme_id'), table_name='journal_audit_plateforme')
    op.drop_index(op.f('ix_journal_audit_plateforme_horodatage'), table_name='journal_audit_plateforme')
    op.drop_index(op.f('ix_journal_audit_plateforme_cible_id'), table_name='journal_audit_plateforme')
    op.drop_index(op.f('ix_journal_audit_plateforme_action'), table_name='journal_audit_plateforme')
    op.drop_index(op.f('ix_journal_audit_plateforme_acteur_id'), table_name='journal_audit_plateforme')
    op.drop_index(op.f('ix_journal_audit_plateforme_acteur_email'), table_name='journal_audit_plateforme')
    op.drop_table('journal_audit_plateforme')
    op.drop_index(op.f('ix_jetons_usage_unique_usage'), table_name='jetons_usage_unique')
    op.drop_index(op.f('ix_jetons_usage_unique_id'), table_name='jetons_usage_unique')
    op.drop_index(op.f('ix_jetons_usage_unique_hash_jeton'), table_name='jetons_usage_unique')
    op.drop_index(op.f('ix_jetons_usage_unique_expire_le'), table_name='jetons_usage_unique')
    op.drop_index(op.f('ix_jetons_usage_unique_cible_id'), table_name='jetons_usage_unique')
    op.drop_table('jetons_usage_unique')
    op.drop_index(op.f('ix_inscriptions_onboarding_tenant_id'), table_name='inscriptions_onboarding')
    op.drop_index(op.f('ix_inscriptions_onboarding_statut'), table_name='inscriptions_onboarding')
    op.drop_index(op.f('ix_inscriptions_onboarding_id'), table_name='inscriptions_onboarding')
    op.drop_index(op.f('ix_inscriptions_onboarding_email'), table_name='inscriptions_onboarding')
    op.drop_table('inscriptions_onboarding')
    op.drop_index(op.f('ix_gabarits_semis_type_gabarit'), table_name='gabarits_semis')
    op.drop_index(op.f('ix_gabarits_semis_id'), table_name='gabarits_semis')
    op.drop_index(op.f('ix_gabarits_semis_code'), table_name='gabarits_semis')
    op.drop_index(op.f('ix_gabarits_semis_actif'), table_name='gabarits_semis')
    op.drop_table('gabarits_semis')
    op.drop_index(op.f('ix_exports_tenant_tenant_id'), table_name='exports_tenant')
    op.drop_index(op.f('ix_exports_tenant_id'), table_name='exports_tenant')
    op.drop_table('exports_tenant')
    op.drop_index(op.f('ix_annonces_id'), table_name='annonces')
    op.drop_index(op.f('ix_annonces_fin'), table_name='annonces')
    op.drop_index(op.f('ix_annonces_debut'), table_name='annonces')
    op.drop_index(op.f('ix_annonces_active'), table_name='annonces')
    op.drop_table('annonces')
    op.drop_index(op.f('ix_acces_support_ticket'), table_name='acces_support')
    op.drop_index(op.f('ix_acces_support_tenant_id'), table_name='acces_support')
    op.drop_index(op.f('ix_acces_support_statut'), table_name='acces_support')
    op.drop_index(op.f('ix_acces_support_id'), table_name='acces_support')
    op.drop_index(op.f('ix_acces_support_expire_le'), table_name='acces_support')
    op.drop_index(op.f('ix_acces_support_agent_id'), table_name='acces_support')
    op.drop_index(op.f('ix_acces_support_agent_email'), table_name='acces_support')
    op.drop_table('acces_support')
    # ### end Alembic commands ###

    # Le déclencheur doit tomber AVANT la table : `DROP TABLE` ne supprime pas
    # la fonction qui y est attachée, elle resterait orpheline en base.
    op.execute("DROP TRIGGER IF EXISTS journal_audit_plateforme_append_only ON journal_audit_plateforme;")
    op.execute("DROP FUNCTION IF EXISTS plateforme_journal_append_only();")
