"""security_sprint_0bis_master

Revision ID: 3c2a49eaec83
Revises: 598f3ad5ecef
Create Date: 2026-10-01 21:05:27.104041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c2a49eaec83'
down_revision: Union[str, None] = '598f3ad5ecef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('super_admin_sessions',
    sa.Column('super_admin_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('est_revoque', sa.Boolean(), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('derniere_activite', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['super_admin_id'], ['super_admins.id'], name=op.f('fk_super_admin_sessions_super_admin_id_super_admins'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_super_admin_sessions'))
    )
    op.create_index(op.f('ix_super_admin_sessions_id'), 'super_admin_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_super_admin_sessions_jti'), 'super_admin_sessions', ['jti'], unique=True)
    op.create_index(op.f('ix_super_admin_sessions_refresh_token'), 'super_admin_sessions', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_super_admin_sessions_super_admin_id'), 'super_admin_sessions', ['super_admin_id'], unique=False)
    op.create_table('utilisateur_index',
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('societe_id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('derniere_connexion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['societe_id'], ['societes.id'], name=op.f('fk_utilisateur_index_societe_id_societes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('email', 'id', name=op.f('pk_utilisateur_index'))
    )
    op.create_index(op.f('ix_utilisateur_index_id'), 'utilisateur_index', ['id'], unique=False)
    op.create_index(op.f('ix_utilisateur_index_societe_id'), 'utilisateur_index', ['societe_id'], unique=False)
    op.add_column('super_admins', sa.Column('tentatives_echouees', sa.Integer(), nullable=False))
    op.add_column('super_admins', sa.Column('verrouille_jusqua', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('super_admins', 'verrouille_jusqua')
    op.drop_column('super_admins', 'tentatives_echouees')
    op.drop_index(op.f('ix_utilisateur_index_societe_id'), table_name='utilisateur_index')
    op.drop_index(op.f('ix_utilisateur_index_id'), table_name='utilisateur_index')
    op.drop_table('utilisateur_index')
    op.drop_index(op.f('ix_super_admin_sessions_super_admin_id'), table_name='super_admin_sessions')
    op.drop_index(op.f('ix_super_admin_sessions_refresh_token'), table_name='super_admin_sessions')
    op.drop_index(op.f('ix_super_admin_sessions_jti'), table_name='super_admin_sessions')
    op.drop_index(op.f('ix_super_admin_sessions_id'), table_name='super_admin_sessions')
    op.drop_table('super_admin_sessions')
    # ### end Alembic commands ###
