"""baseline_master_schema

Revision ID: 598f3ad5ecef
Revises: 
Create Date: 2026-09-13 22:53:55.462421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '598f3ad5ecef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs_global',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('auteur_email', sa.String(length=150), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('cible_id', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs_global'))
    )
    op.create_index(op.f('ix_audit_logs_global_id'), 'audit_logs_global', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_global_timestamp'), 'audit_logs_global', ['timestamp'], unique=False)
    op.create_table('societes',
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('ninea', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('adresse_siege', sa.Text(), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('site_web', sa.String(length=200), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_societes'))
    )
    op.create_index(op.f('ix_societes_id'), 'societes', ['id'], unique=False)
    op.create_index(op.f('ix_societes_ninea'), 'societes', ['ninea'], unique=True)
    op.create_index(op.f('ix_societes_nom'), 'societes', ['nom'], unique=False)
    op.create_table('super_admins',
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('nom_complet', sa.String(length=150), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('dernier_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_super_admins'))
    )
    op.create_index(op.f('ix_super_admins_email'), 'super_admins', ['email'], unique=True)
    op.create_index(op.f('ix_super_admins_id'), 'super_admins', ['id'], unique=False)
    op.create_table('tenants_db',
    sa.Column('societe_id', sa.UUID(), nullable=False),
    sa.Column('db_name', sa.String(length=100), nullable=False),
    sa.Column('db_host', sa.String(length=150), nullable=False),
    sa.Column('db_port', sa.Integer(), nullable=False),
    sa.Column('db_user', sa.String(length=100), nullable=False),
    sa.Column('db_password', sa.String(length=200), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['societe_id'], ['societes.id'], name=op.f('fk_tenants_db_societe_id_societes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants_db')),
    sa.UniqueConstraint('db_name', name=op.f('uq_tenants_db_db_name')),
    sa.UniqueConstraint('societe_id', name=op.f('uq_tenants_db_societe_id'))
    )
    op.create_index(op.f('ix_tenants_db_id'), 'tenants_db', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_db_id'), table_name='tenants_db')
    op.drop_table('tenants_db')
    op.drop_index(op.f('ix_super_admins_id'), table_name='super_admins')
    op.drop_index(op.f('ix_super_admins_email'), table_name='super_admins')
    op.drop_table('super_admins')
    op.drop_index(op.f('ix_societes_nom'), table_name='societes')
    op.drop_index(op.f('ix_societes_ninea'), table_name='societes')
    op.drop_index(op.f('ix_societes_id'), table_name='societes')
    op.drop_table('societes')
    op.drop_index(op.f('ix_audit_logs_global_timestamp'), table_name='audit_logs_global')
    op.drop_index(op.f('ix_audit_logs_global_id'), table_name='audit_logs_global')
    op.drop_table('audit_logs_global')
    # ### end Alembic commands ###
